# Generated by Django 4.1.3 on 2022-12-18 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part1', to=settings.AUTH_USER_MODEL)),
                ('part2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('conv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatting.conversation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
