# Generated by Django 4.1.3 on 2022-12-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profiles/Default.jpg', upload_to='profiles'),
        ),
    ]
